[package]
name = "drill"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
ratatui = "0.30.2"
tokio = { version = "1.53.1", features = ["full"] }
vte = "0.15.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lib-rust = {path = "../lib-rust"}
syntect = "5.3.0"

lancedb = { version = "0.38.0", features = ["remote"] }
arrow-array = "58.4.0"
futures = "0.3"
reqwest = {version = "0.13.5", features = ["rustls", "blocking", "json"]}
base64 = "0.22"